apiVersion: v1
kind: Pod                   # type of K8s object which is in this case a pod.
metadata:
  name: lab2                # name of pod
  labels:
    app: frontend           # label pod with "app:frontend"
spec:
  containers:
  - name: nginx
    image: nginx:latest     # image name:image version which will be downloaded from dockerhub
    ports:
    - containerPort: 80     # open ports in the container
    env:                    # environment variables
      - name: USER
        value: "username"

